// apps/web/src/components/admin/CreateProfessorCard.jsx
import { useState } from "react";
import { adminApi } from "../../api";
import { useToast } from "../../context/useToast";
import { PasswordInput } from "../ui/PasswordInput";

export function CreateProfessorCard({ onCreated }) {
  const [fullName, setFullName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [createdResult, setCreatedResult] = useState(null);
  const [copied, setCopied] = useState(false);
  const { showToast } = useToast();

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      const res = await adminApi.createProfessor({
        fullName,
        email,
        password: password.trim() || undefined,
      });
      showToast(
        "success",
        `Professor account created for ${email}. Invitation email dispatched.`,
      );
      setCreatedResult(res);
      setFullName("");
      setEmail("");
      setPassword("");
      if (onCreated) onCreated();
    } catch (err) {
      showToast("error", err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!createdResult?.tempPassword) return;
    navigator.clipboard.writeText(createdResult.tempPassword);
    setCopied(true);
    showToast("success", "Password copied to clipboard!");
    setTimeout(() => setCopied(false), 2500);
  };

  if (createdResult) {
    return (
      <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 max-w-lg space-y-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-emerald-50 text-emerald-600 flex items-center justify-center text-xl font-bold">
            ✓
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-900">Professor Account Created</h3>
            <p className="text-xs text-slate-500">Credentials have been generated and dispatched</p>
          </div>
        </div>

        <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 space-y-3">
          <div>
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 block">
              Professor Name & Email
            </span>
            <p className="text-sm font-semibold text-slate-800">{createdResult.full_name}</p>
            <p className="text-xs font-mono text-slate-500">{createdResult.email}</p>
          </div>

          <div>
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 block">
              {createdResult.isAutoGenerated ? "Auto-Generated Temporary Password" : "Set Password"}
            </span>
            <div className="flex items-center gap-2 mt-1">
              <code className="px-3 py-2 bg-white border border-slate-300 rounded-lg text-sm font-mono font-bold text-indigo-700 flex-1 select-all">
                {createdResult.tempPassword}
              </code>
              <button
                type="button"
                onClick={handleCopy}
                className="px-3 py-2 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 font-semibold text-xs rounded-lg transition shrink-0"
              >
                {copied ? "✓ Copied!" : "📋 Copy"}
              </button>
            </div>
          </div>

          {createdResult.isAutoGenerated && (
            <p className="text-[11px] text-amber-700 bg-amber-50 p-2 rounded-lg border border-amber-200">
              💡 The professor will be required to change this temporary password upon their first login.
            </p>
          )}
        </div>

        <button
          type="button"
          onClick={() => setCreatedResult(null)}
          className="w-full py-2 bg-slate-900 hover:bg-black text-white text-xs font-semibold rounded-xl transition"
        >
          Create Another Professor
        </button>
      </div>
    );
  }

  return (
    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 max-w-lg">
      <h3 className="text-base font-bold text-slate-900 mb-1">
        Create Professor Account
      </h3>
      <p className="text-xs text-slate-500 mb-4">
        Create a new professor account. You can specify a custom password or leave it blank to auto-generate one.
      </p>
      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="block text-xs font-bold uppercase tracking-wider text-slate-600 mb-1">
            Professor Full Name
          </label>
          <input
            type="text"
            required
            placeholder="e.g. Dr. Alan Turing"
            value={fullName}
            onChange={(e) => setFullName(e.target.value)}
            className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-300 rounded-xl text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
          />
        </div>
        <div>
          <label className="block text-xs font-bold uppercase tracking-wider text-slate-600 mb-1">
            Email Address
          </label>
          <input
            type="email"
            required
            placeholder="prof@university.edu"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-300 rounded-xl text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
          />
        </div>
        <div>
          <div className="flex items-center justify-between mb-1">
            <label className="block text-xs font-bold uppercase tracking-wider text-slate-600">
              Initial Password (Optional)
            </label>
            <span className="text-[11px] text-slate-400">Leave blank for auto-gen</span>
          </div>
          <PasswordInput
            minLength={8}
            placeholder="Optional password (min 8 chars)..."
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
        </div>
        <button
          type="submit"
          disabled={loading}
          className="w-full py-2.5 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white font-semibold rounded-xl shadow-xs text-sm transition"
        >
          {loading ? "Creating..." : "Create Professor Account"}
        </button>
      </form>
    </div>
  );
}
